code --install-extension aaron-bond.better-comments
code --install-extension antfu.icons-carbon
code --install-extension artdiniz.quitcontrol-vscode
code --install-extension bierner.comment-tagged-templates
code --install-extension bierner.folder-source-actions
code --install-extension bierner.github-markdown-preview
code --install-extension bierner.markdown-checkbox
code --install-extension bierner.markdown-emoji
code --install-extension bierner.markdown-footnotes
code --install-extension bierner.markdown-mermaid
code --install-extension bierner.markdown-preview-github-styles
code --install-extension bierner.markdown-yaml-preamble
code --install-extension bungcip.better-toml
code --install-extension christian-kohler.path-intellisense
code --install-extension codezombiech.gitignore
code --install-extension dakara.transformer
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension Divlo.vscode-styled-jsx-languageserver
code --install-extension Divlo.vscode-styled-jsx-syntax
code --install-extension drKnoxy.eslint-disable-snippets
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension foxundermoon.shell-format
code --install-extension genieai.chatgpt-vscode
code --install-extension GitHub.github-vscode-theme
code --install-extension golang.go
code --install-extension jock.svg
code --install-extension mikestead.dotenv
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension naumovs.color-highlight
code --install-extension pustelto.bracketeer
code --install-extension redhat.vscode-commons
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension richie5um2.vscode-sort-json
code --install-extension sburg.vscode-javascript-booster
code --install-extension WallabyJs.quokka-vscode
code --install-extension wmaurer.change-case
code --install-extension yzhang.markdown-all-in-one
code --install-extension zachhardesty.convert-object-to-jsx-vscode
